### ISSUE TITLE
Hotfixes

### ISSUE THREAD

**Issue by raney24** [raney24/brokeSpoke#8]
- Edit people is giving 500 error. /edit-people/972
- Generate report list gives 500 error.  /charts

**Comment by raney24** [comment]
People -> 
Vogel
Kirkwood

**Comment by WillGarman** [comment]
Ok so some findings for the day:

### The error message for both errors is: `Exception Value: | can't compare offset-naive and offset-aware datetimes`

Researching this error seems to be that the time zones are getting mixed up during the comparisons.
[django 1.4 - can't compare offset-naive and offset-aware datetimes](https://stackoverflow.com/questions/10652819/django-1-4-cant-compare-offset-naive-and-offset-aware-datetimes)
[Can't compare naive and aware datetime.now() <= challenge.datetime_end](https://stackoverflow.com/questions/15307623/cant-compare-naive-and-aware-datetime-now-challenge-datetime-end)

I have also noticed that if you change the lines with errors (or where the variables get made) to add `timezone.make_aware`, the Heroku server will fail with "Application Error" (and not load the site). 

I also noticed if you change `USE_TZ = True` to `False` it will also cause Heroku to crash.

For the "edit-people" error it is happening on line ~`1028` in `/app/dashboard/views.py`: 
- `if datetime.datetime.strptime(bike['date'],'%m/%d/%Y %I:%M %p') > (timezone.now()-datetime.timedelta(days=365)):`
A possible fix could be (Caused Heroku crash):
- `if timezone.make_aware(datetime.datetime.strptime(bike['date'],'%m/%d/%Y %I:%M %p')) > (timezone.make_aware(timezone.now()-datetime.timedelta(days=365))):`

For the "generate-report" error it is happening on line ~`1328` in `/app/dashboard/views.py`:
- ` if membershipDateFormatted >  todayDate:`
A possible fix could be (Caused Heroku crash):
- `if timezone.make_aware(membershipDateFormatted) >  timezone.make_aware(todayDate):`

Also an interesting thing I have noticed is running the site locally with `USE_TZ = False` (instead of `True`) I don't seem to have _any errors_ anywhere. Worth looking into finding a way to try this (_trying tomorrow_) on the live site without getting Heroku errors. 

@raney24

**Comment by raney24** [comment]
@WillGarman Looks like it is solved for me. 

I can talk more about this in person. But when we first built the app, time was handled parsing a string into a Time object and then saved into the DB as a string. Which was not the right way since there is a Time model object in Django. 

I refactored it a while back because of some other errors to use Time objects instead, I thought I caught everything but I guess not. 

Good debugging and looking into this. I couldn't find anymore users with 500 errors, could you?

**Comment by raney24** [comment]
I also am able to do `Generate Report List`, maybe what you changed also fixed that as well?

**Comment by whatnotery** [comment]
I believe based on a conversation with @lukebox87 on Sunday that these issues are now resolved as far as we can tell

**Comment by lukebox87** [comment]
@whatnotery it never resolved. Charlotte's still logged in

**Comment by whatnotery** [comment]
@lukebox87 I believe that's a different issue than the errors discussed in this thread? This thread is for the two issues discussed at the in person meeting

**Comment by lukebox87** [comment]
Dang. You're right. Sorry about that!

**Comment by WillGarman** [comment]
@raney24 I could not find any other errors happening anywhere else!

**Comment by WillGarman** [comment]
Update I noticed it is giving the original 500 error when try to go to 
- [My user](https://portal.brokespoke.org/edit-people/2851/)
- [Kyle's user](https://portal.brokespoke.org/edit-people/5/)

I just made my account and it donst seem to be working so it could also be problems with new accounts, I'm trying to think of what mine and kyles have in common that would cause them both to error

**Comment by raney24** [comment]
@lukebox87 Are we good to close this? I think the issue has been resolved.

**Comment by lukebox87** [comment]
Yep. This is clear. Thanks!
